### ISSUE TITLE
Не мапится по имени дата

### ISSUE THREAD

**Issue by makaresh** [AgentGregory/parser#12]
https://github.com/AgentGregory/parser/blob/1e5ab1db7645116b2196d480835fff847a0bb347/src/main/java/ru/agentgregory/parser/model/Article.java#L25

см ишус#11

в миграции у тебя написано publishdata (некорректное название (data-данные, date-дата), думаю, ты просто опечатался, такое часто встречается)))) )
хибернейт по дефолту мапит поля и колонки таким образом поле класса publishDate -> колонка publish_date

**Comment by AgentGregory** [comment]
тоже поменял, опечатался
